from typing import Protocol

from banking_service.domain.accounts import Account
from banking_service.domain.transactions import Transaction


class AccountRepository(Protocol):
    def get(self, account_id: str) -> Account | None: ...
    def get_by_owner(self, owner_id: str) -> list[Account]: ...
    def list_all(self) -> list[Account]: ...
    def add(self, account: Account) -> None: ...
    def update(self, account: Account) -> None: ...


class TransactionRepository(Protocol):
    def add(self, tx: Transaction) -> None: ...
    def list_for_account(self, account_id: str) -> list[Transaction]: ...
    def list_all(self) -> list[Transaction]: ...


class AuditLog(Protocol):
    def record(self, event: dict) -> None: ...


class Clock(Protocol):
    def now(self) -> int: ...
