from typing import Protocol

from auth_service.domain.refresh import RefreshRecord
from auth_service.domain.users import User


class UserRepository(Protocol):
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_id(self, user_id: str) -> User | None: ...
    def add(self, user: User) -> None: ...


class RefreshTokenStore(Protocol):
    def add(self, record: RefreshRecord) -> None: ...
    def get(self, token_hash: str) -> RefreshRecord | None: ...
    def remove(self, token_hash: str) -> None: ...


class AuditLog(Protocol):
    def record(self, event: dict) -> None: ...


class Clock(Protocol):
    def now(self) -> int: ...
